language: python
python:
  - "3.5"
sudo: false
branches:
  only:
  - master
language: python
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - make publish
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: dicasdeprogramacao.com.br
    region: sa-east-1
    skip_cleanup: true
    local-dir: output
    acl: public_read
    detect_encoding: true
notifications:
    email:
        on_failure: always
